const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const os = require('node:os');
const http = require('node:http');
const artifactDir = fs.mkdtempSync(path.join(os.tmpdir(), 'todo-board-check-'));
const root = path.resolve(__dirname, '../src');
const mime = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.svg':'image/svg+xml', '.png':'image/png', '.webmanifest':'application/manifest+json' };
const server = http.createServer(async (req,res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
    const file = path.resolve(root, '.' + (pathname === '/' ? '/index.html' : pathname));
    if (!file.startsWith(root + path.sep)) {res.writeHead(403);res.end();return;}
    const body = await fs.promises.readFile(file);
    res.writeHead(200, {'Content-Type':mime[path.extname(file)] || 'application/octet-stream', 'Cache-Control':'no-cache'});res.end(body);
  } catch {res.writeHead(404);res.end();}
});
const binary = process.env.BROWSER_BINARY || [
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
  '/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
].find(file=>fs.existsSync(file));
if (!binary) throw new Error('Install Chrome/Chromium or set BROWSER_BINARY.');
const assert = require('node:assert/strict');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const profile = path.join(os.tmpdir(), 'board-qa-' + require('node:crypto').randomUUID().slice(0,8));
const child = spawn(binary, ['--headless=new', '--disable-extensions', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows', '--no-first-run', '--no-default-browser-check', '--remote-debugging-port=0', '--user-data-dir=' + profile, 'about:blank'], { windowsHide: true, stdio: 'ignore' });
let socket;
(async () => {
  try {
    const activePort = path.join(profile, 'DevToolsActivePort');
    for (let i = 0; i < 100 && !fs.existsSync(activePort); i++) await pause(100);
    assert(fs.existsSync(activePort), 'Chrome debugging connection started');
    const port = fs.readFileSync(activePort, 'utf8').split('\n')[0];
    const target = await (await fetch('http://127.0.0.1:' + port + '/json/new?about:blank', { method: 'PUT' })).json();
    socket = new WebSocket(target.webSocketDebuggerUrl);
    await new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', reject, { once: true }); });
    const pending = new Map();
    const errors = [];
    let nextId = 0;
    socket.addEventListener('message', event => {
      const result = JSON.parse(event.data);
      if (result.method === 'Runtime.exceptionThrown') errors.push(result.params.exceptionDetails.text);
      if (result.id && pending.has(result.id)) {
        const { resolve, reject } = pending.get(result.id);
        pending.delete(result.id);
        result.error ? reject(new Error(JSON.stringify(result.error))) : resolve(result.result);
      }
    });
    const send = (method, params = {}) => new Promise((resolve,reject) => {
      const id=++nextId;
      const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},15000);
      pending.set(id,{resolve:value=>{clearTimeout(timeout);resolve(value)},reject:error=>{clearTimeout(timeout);reject(error)}});
      socket.send(JSON.stringify({id,method,params}));
    });
    const evaluate = async expression => {
      const result = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
      if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
      return result.result.value;
    };
    await send('Runtime.enable');
    await send('Page.enable'); await send('Page.bringToFront');
    await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 800, deviceScaleFactor: 1, mobile: false });
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
    const url = 'http://127.0.0.1:' + server.address().port + '/index.html';
    const waitFor = async expression => { for(let i=0;i<100;i++){if(await evaluate(expression))return;await pause(50);}throw new Error('Timed out: '+expression); };
    const warm = async () => {await pause(750);await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');};
    const stored=()=>evaluate('JSON.parse(localStorage.getItem("my-todo-board-v1"))');
    const click=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+').click()');
    const openPanels=async()=>{if(await evaluate('document.querySelector("#focus-mode").getAttribute("aria-pressed")==="true"'))await click('#focus-mode');};
    const point=selector=>evaluate('(()=>{const b=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:b.left+b.width/2,y:b.top+b.height/2}})()');
    const mouse=(type,p)=>send('Input.dispatchMouseEvent',{type,button:type==='mouseMoved'?'none':'left',buttons:type==='mouseReleased'?0:1,clickCount:1,...p});
    const pointerClick=async selector=>{const p=await point(selector);await mouse('mousePressed',p);await mouse('mouseReleased',p);};
    const key=async(name,code=name,virtual=0)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key:name,code,windowsVirtualKeyCode:virtual,...(name==='Enter'?{text:'\r'}:name===' '?{text:' '}:{})});await send('Input.dispatchKeyEvent',{type:'keyUp',key:name,code,windowsVirtualKeyCode:virtual});};
    const drag=async(selector,dx,dy)=>{const p=await point(selector);await mouse('mouseMoved',p);await mouse('mousePressed',p);await pause(230);await mouse('mouseMoved',{x:p.x+dx,y:p.y+dy});await pause(50);await mouse('mouseReleased',{x:p.x+dx,y:p.y+dy});await pause(250);};
    const submitName=async name=>{await evaluate('document.querySelector("#name-input").value='+JSON.stringify(name)+';document.querySelector("#name-form").requestSubmit()');await warm();};
    const add=async(selector,text,date='')=>{await evaluate('(()=>{const p=document.querySelector('+JSON.stringify(selector)+');p.querySelector(".task-input").value='+JSON.stringify(text)+';p.querySelector(".due-date-input").value='+JSON.stringify(date)+';p.querySelector(".task-form").requestSubmit()})()');await pause(350);};
    await send('Page.navigate',{url});
    await waitFor('window.boardWorkspace && document.querySelector(".paper")');
    await send('Page.navigate',{url:url.replace('index.html','manifest.webmanifest')}); await pause(250);
    await evaluate('localStorage.removeItem("my-todo-board-v1");localStorage.setItem("tasks",JSON.stringify(Array.from({length:8},(_,i)=>({id:i+1,text:"Task "+(i+1),completed:false,dueDate:i<2?new Date().getFullYear()+"-"+String(new Date().getMonth()+1).padStart(2,"0")+"-"+String(new Date().getDate()).padStart(2,"0"):""}))));location.href="/index.html"');
    await waitFor('document.querySelectorAll(".task-item").length===8');
    assert(await evaluate('document.querySelector(".paper").classList.contains("is-entering")'),'Opening animation starts');
    await warm();
    let initial=await stored();const groupA=initial.activeGroupId, first=initial.cards[0].id;
    assert.equal(initial.cards.length,1);assert.equal(initial.cards[0].tasks.length,8);assert.equal(await evaluate('JSON.parse(localStorage.getItem("tasks")).length'),8);
    assert(await evaluate('(()=>{const l=document.querySelector(".task-list");return l.clientHeight<=252&&l.scrollHeight>l.clientHeight&&getComputedStyle(l).overflowY==="auto"})()'));
    assert(await evaluate('getComputedStyle(document.querySelector(".task-text")).color==="rgb(0, 0, 0)"'));
    console.log('PASS migration, entry bounce, black ink, capped scrolling, and retained legacy data');
    const paperBounds=()=>evaluate('(()=>{const b=document.querySelector(".paper:not([hidden])").getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height}})()');
    const fixedPaper=await paperBounds(),fixedCamera=initial.groups[0].camera;
    assert(await evaluate('document.body.classList.contains("sidebar-open")&&document.body.classList.contains("toolbar-open")'),'Both desktop panels start open');
    assert(await evaluate('!document.querySelector(".panel-tab, #sidebar-toggle, #toolbar-toggle, .board-hint")'),'Chevron controls and both drag hints are removed');
    await pointerClick('#focus-mode');await pause(65);
    assert(await evaluate('(()=>{const p=document.querySelector("#sidebar"),b=p.getBoundingClientRect(),t=document.querySelector("#workspace-toolbar"),r=t.getBoundingClientRect();return p.inert&&t.inert&&b.left<0&&b.right>0&&r.top<0&&r.bottom>0})()'),'Focus mode smoothly closes both panels and immediately removes their keyboard focus');
    await pause(300);assert.deepEqual(await paperBounds(),fixedPaper,'Closing both panels leaves the paper in place');
    assert.deepEqual((await stored()).groups[0].camera,fixedCamera,'Panel toggles do not change the saved camera');
    assert(await evaluate('document.querySelector("#focus-mode").getBoundingClientRect().right<=innerWidth&&document.querySelector("#board-viewport").getBoundingClientRect().left===0'),'Focus button remains visible over the full board');
    await send('Page.reload');await waitFor('window.boardWorkspace&&document.querySelector(".paper")');await warm();
    assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert&&document.querySelector("#focus-mode").getAttribute("aria-pressed")==="true"'),'Refresh restores closed panels');
    assert.deepEqual(await paperBounds(),fixedPaper,'Refreshing closed panels retains the paper position');
    let panelShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'panels-focus-desktop.png'),Buffer.from(panelShot.data,'base64'));
    const hoverFocus=await point('#focus-mode');await send('Input.dispatchMouseEvent',{type:'mouseMoved',buttons:0,...hoverFocus});await pause(180);
    assert(await evaluate('!document.querySelector("#focus-tooltip, .panel-tooltip")&&document.querySelector("#sidebar").inert'),'Hover shows no focus-mode tooltip and keeps the panels closed');
    await evaluate('document.querySelector("#focus-mode").focus()');await key('Enter','Enter',13);await pause(350);
    assert(await evaluate('(()=>{const b=document.querySelector("#focus-mode"),s=getComputedStyle(b);return !document.querySelector("#sidebar").inert&&!document.querySelector("#workspace-toolbar").inert&&document.activeElement===b&&s.backgroundColor==="rgba(0, 0, 0, 0)"&&s.boxShadow==="none"})()'),'Enter opens both panels and keeps keyboard focus on the plain icon');
    await key(' ','Space',32);await pause(300);assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert'),'Space toggles focus mode');
    await key(' ','Space',32);await pause(300);
    await evaluate('document.querySelector(".group-button").focus()');await key('Escape','Escape',27);assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert&&document.activeElement.id==="focus-mode"'),'Escape closes focused panels and returns focus to the remaining control');await pause(300);
    await pointerClick('#focus-mode');await pause(65);await click('#focus-mode');await pause(65);await click('#focus-mode');await pause(300);
    assert(await evaluate('document.querySelector("#sidebar").getBoundingClientRect().left===0&&document.querySelector("#workspace-toolbar").getBoundingClientRect().top===0'),'Rapid focus-mode clicks finish with both panels open');
    assert.deepEqual(await paperBounds(),fixedPaper);assert(await evaluate('document.documentElement.scrollWidth===innerWidth'),'Panel transitions create no horizontal page scrollbar');
    console.log('PASS focus-only panel control, removed chevrons/hints, smooth reversals, stable paper/camera, keyboard controls and persistent visibility');
    await evaluate('window.survivor=document.querySelectorAll(".task-item")[1];window.beforeY=survivor.getBoundingClientRect().top;document.querySelector(".delete-btn").click()');
    await pause(330);assert(await evaluate('document.querySelector(".task-item")===survivor'));
    assert(await evaluate('survivor.getAnimations().length>0'),'Surviving rows animate');
    await pause(400);assert(await evaluate('document.querySelector(".task-list").getAnimations().length===0'));
    await click('.task-checkbox');await pause(70);
    assert(await evaluate('document.querySelector(".task-checkbox").checked && parseFloat(getComputedStyle(document.querySelector(".task-checkbox"),"::after").opacity)>0 && parseFloat(getComputedStyle(document.querySelector(".task-checkbox"),"::after").opacity)<1'));
    assert.equal(await evaluate('document.querySelector(".counter-number").dataset.value'),'6');await pause(400);
    await click('[data-filter="completed"]');assert.equal(await evaluate('document.querySelectorAll(".task-item").length'),1);
    await click('[data-filter="all"]');
    await click('.edit-btn');await evaluate('document.querySelector(".edit-input").value="Edited task";document.querySelector(".edit-input").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}))');
    assert.equal((await stored()).cards[0].tasks[0].text,'Edited task');
    console.log('PASS surviving row motion, checkbox transition, rolling counter, filters, and task editing');
    await drag('.paper-drag-handle',120,70);let moved=await stored();
    assert(Math.abs(moved.cards[0].x-initial.cards[0].x-120)<1);assert(Math.abs(moved.cards[0].y-initial.cards[0].y-70)<1);
    const savedCamera=moved.groups[0].camera;
    await send('Page.reload');await waitFor('document.querySelectorAll(".task-item").length===7');await warm();
    const restored=await stored();assert.equal(restored.cards[0].x,moved.cards[0].x);assert.deepEqual(restored.groups[0].camera,savedCamera);
    await click('#toggle-create');assert(await evaluate('!document.querySelector("#create-menu").hidden'));await click('#create-card');await submitName('Second paper');
    let many=await stored();assert.equal(many.cards.length,2);
    assert(await evaluate('(()=>{const s=JSON.parse(localStorage.getItem("my-todo-board-v1"));const [a,b]=s.cards;const ea=document.querySelectorAll(".paper")[0],eb=document.querySelectorAll(".paper")[1];return !(a.x<b.x+eb.offsetWidth&&a.x+ea.offsetWidth>b.x&&a.y<b.y+eb.offsetHeight&&a.y+ea.offsetHeight>b.y)})()'),'New card avoids existing card');
    const second=many.cards[1].id;const secondSelector='.paper[data-card-id="'+second+'"]';
    await add(secondSelector,'Second task');
    assert.equal((await stored()).cards.find(c=>c.id===second).tasks.length,1);assert.equal((await stored()).cards.find(c=>c.id===first).tasks.length,7);
    await evaluate('document.querySelectorAll(".paper")[0].dispatchEvent(new PointerEvent("pointerenter"))');await pause(200);
    assert((await stored()).cards[0].z>(await stored()).cards[1].z);
    await evaluate('document.querySelector("#board-viewport").focus();document.querySelectorAll(".paper")[1].querySelector(".task-input").focus({preventScroll:true})');await pause(200);
    assert((await stored()).cards[1].z>(await stored()).cards[0].z);
    console.log('PASS persistent drag/camera, multiple independent cards, empty-space spawning, hover/focus stacking');
    const visibleCamera=()=>evaluate('(()=>{const m=new DOMMatrixReadOnly(getComputedStyle(document.querySelector("#board-world")).transform);return {x:m.e,y:m.f,zoom:m.a}})()');
    const cameraDistance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
    const firstLink='.sidebar-card-link[data-link-id="'+first+'"]',secondLink='.sidebar-card-link[data-link-id="'+second+'"]';
    const beforeNavigation=await visibleCamera();await click(firstLink);await pause(70);
    const halfwayNavigation=await visibleCamera(),navigationTarget=(await stored()).groups[0].camera;
    assert(cameraDistance(halfwayNavigation,beforeNavigation)>1&&cameraDistance(halfwayNavigation,navigationTarget)>1,'Sidebar navigation passes through intermediate board positions');
    assert(await evaluate('document.querySelector("#board-world").getAnimations().some(a=>a.playState==="running")'));
    await pause(400);assert(cameraDistance(await visibleCamera(),navigationTarget)<.01,'Camera arrives at the chosen paper');
    assert.equal(await evaluate('document.activeElement.closest(".paper").dataset.cardId'),first,'Chosen paper receives keyboard focus');
    await click(secondLink);await pause(70);const beforeRetarget=await visibleCamera();await click(firstLink);
    const retargetedCamera=await visibleCamera();
    assert(cameraDistance(retargetedCamera,beforeRetarget)<cameraDistance(beforeRetarget,navigationTarget)*.4,'Rapid clicks resume near the visible position instead of jumping to the destination');
    await click(secondLink);await pause(470);assert.equal(await evaluate('document.activeElement.closest(".paper").dataset.cardId'),second);
    assert.equal(await evaluate('document.querySelector("#board-world").getAnimations().length'),0,'Rapid navigation leaves no camera animations');
    await click(firstLink);await pause(70);const beforeGrab=await visibleCamera(),panAnchor={x:280,y:700};
    await mouse('mousePressed',panAnchor);await pause(40);
    assert(cameraDistance(await visibleCamera(),beforeGrab)<60,'Starting a pan holds the current visual position');
    assert.equal(await evaluate('document.querySelector("#board-world").getAnimations().length'),0,'Direct manipulation interrupts navigation');
    const grabbedCamera=await visibleCamera();await mouse('mouseMoved',{x:panAnchor.x+35,y:panAnchor.y+20});await mouse('mouseReleased',{x:panAnchor.x+35,y:panAnchor.y+20});
    const afterGrab=await visibleCamera();assert(Math.abs(afterGrab.x-grabbedCamera.x-35)<1&&Math.abs(afterGrab.y-grabbedCamera.y-20)<1,'Panning follows the pointer immediately after interruption');
    await click(secondLink);await pause(470);
    await click(firstLink);await pause(180);
    const paperGrab=await point('.paper[data-card-id="'+first+'"] .paper-drag-handle'),paperBefore=(await stored()).cards.find(c=>c.id===first);
    assert.equal(await evaluate('document.elementFromPoint('+paperGrab.x+','+paperGrab.y+')?.closest(".paper")?.dataset.cardId'),first,'Grab the paper after its header enters the viewport');
    await mouse('mousePressed',paperGrab);const dragZoom=await evaluate('window.boardWorkspace.zoom');
    assert.equal(await evaluate('document.querySelector("#board-world").getAnimations().length'),0,'Grabbing a paper also interrupts navigation');
    await mouse('mouseMoved',{x:paperGrab.x+24,y:paperGrab.y+12});await mouse('mouseReleased',{x:paperGrab.x+24,y:paperGrab.y+12});
    const paperAfter=(await stored()).cards.find(c=>c.id===first);
    assert(Math.abs(paperAfter.x-paperBefore.x-24/dragZoom)<1&&Math.abs(paperAfter.y-paperBefore.y-12/dragZoom)<1,'Paper drag uses the visible zoom after interruption');
    await click(secondLink);await pause(470);
    console.log('PASS smooth sidebar camera travel, final focus, rapid retargeting, and immediate pan/paper interruption');
    const beforeZoom=await stored();await evaluate('document.querySelector("#board-zoom").value="150";document.querySelector("#board-zoom").dispatchEvent(new Event("input",{bubbles:true}))');await pause(200);
    assert(Math.abs(await evaluate('window.boardWorkspace.zoom')-2/3)<.001);
    assert.equal(await evaluate('document.querySelector("#zoom-label").textContent'),'150%');
    await drag(secondSelector+' .paper-drag-handle',90,30);let zoomDragged=await stored();
    assert(Math.abs(zoomDragged.cards[1].x-beforeZoom.cards[1].x-135)<1);
    assert(Math.abs(zoomDragged.cards[1].y-beforeZoom.cards[1].y-45)<1);
    const boardPoint={x:280,y:150};const beforePan=(await stored()).groups[0].camera;
    await mouse('mousePressed',boardPoint);await mouse('mouseMoved',{x:330,y:180});await mouse('mouseReleased',{x:330,y:180});await pause(200);
    const afterPan=(await stored()).groups[0].camera;assert(Math.abs(afterPan.x-beforePan.x-50)<1);assert(Math.abs(afterPan.y-beforePan.y-30)<1);
    console.log('PASS inverse extent zoom, world-coordinate drag at zoom, four-way board pan');
    await click('#add-group');await submitName('Work');const groupB=(await stored()).activeGroupId;
    assert.notEqual(groupA,groupB);assert.equal(await evaluate('document.querySelectorAll(".paper:not([hidden])").length'),0);
    await click('#empty-create');await submitName('Work paper');
    const workCard=(await stored()).cards[2];const workSelector='.paper[data-card-id="'+workCard.id+'"]';
    const due=(await stored()).cards[0].tasks[0].dueDate;await add(workSelector,'Work deadline',due);
    const workLink='.sidebar-card-link[data-link-id="'+workCard.id+'"]';
    await click(firstLink);await pause(70);
    assert.equal((await stored()).activeGroupId,groupA);
    assert(await evaluate('(()=>{const g=document.querySelector(".group-transition");return g&&g.inert&&g.getAttribute("aria-hidden")==="true"&&!g.querySelector("[id], [aria-live], [data-card-id], [data-asset-id]")&&Number(getComputedStyle(document.querySelector("#card-layer")).opacity)>0&&Number(getComputedStyle(document.querySelector("#card-layer")).opacity)<1})()'),'Group switches fade outgoing inert snapshots and incoming papers');
    await click(workLink);await click(firstLink);await click(workLink);await pause(470);
    assert.equal((await stored()).activeGroupId,groupB);assert.equal(await evaluate('document.activeElement.closest(".paper").dataset.cardId'),workCard.id);
    assert(await evaluate('!document.querySelector(".group-transition")&&document.querySelector("#card-layer").getAnimations().length===0&&document.querySelector("#asset-layer").getAnimations().length===0'),'Rapid group navigation cleans up all snapshots and fades');
    console.log('PASS smooth group changes, inert outgoing content, final selected group/card, and rapid cleanup');
    await click('#toggle-create');await pause(70);
    assert(await evaluate('(()=>{const e=document.querySelector("#create-menu"),s=getComputedStyle(e);return !e.hidden&&!e.inert&&Number(s.opacity)>0&&Number(s.opacity)<1&&e.getAnimations().some(a=>a.playState==="running")})()'),'Create menu fades in');
    await click('#toggle-create');await pause(60);
    assert(await evaluate('(()=>{const e=document.querySelector("#create-menu");return !e.hidden&&e.inert&&Number(getComputedStyle(e).opacity)<1&&document.querySelector("#toggle-create").getAttribute("aria-expanded")==="false"})()'),'Create menu fades out without remaining interactive');
    await pause(180);assert(await evaluate('document.querySelector("#create-menu").hidden'));
    await evaluate('for(let i=0;i<3;i++)document.querySelector("#toggle-create").click()');await pause(300);
    assert(await evaluate('!document.querySelector("#create-menu").hidden&&document.querySelector("#toggle-create").getAttribute("aria-expanded")==="true"&&document.querySelector("#create-menu").getAnimations().length===0'),'Rapid toggles settle on the last state');
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await pause(200);
    assert(await evaluate('document.querySelector("#create-menu").hidden&&document.activeElement===document.querySelector("#toggle-create")'));
    for(const [choice,dialog] of [['#create-card','#name-dialog'],['#open-assets','#asset-dialog']]) {
      await click('#toggle-create');await click(choice);await pause(70);
      assert(await evaluate('(()=>{const e=document.querySelector('+JSON.stringify(dialog)+');return e.open&&Number(getComputedStyle(e).opacity)>0&&Number(getComputedStyle(e).opacity)<1&&e.getAnimations().some(a=>a.playState==="running")})()'),'The selected add panel appears smoothly');
      await click(dialog+' .dialog-close');await pause(180);
    }
    await click('#open-calendar');await pause(70);
    assert(await evaluate('Number(getComputedStyle(document.querySelector("#calendar-dialog")).opacity)>0&&Number(getComputedStyle(document.querySelector("#calendar-dialog")).opacity)<1'),'Calendar dialog appears smoothly');
    assert.equal(await evaluate('document.querySelectorAll("#calendar-tasks .calendar-task").length'),1);
    await pause(250);
    assert(await evaluate('document.querySelectorAll("select").length===2&&document.querySelectorAll(".dropdown-trigger").length===2&&[...document.querySelectorAll("select")].every(s=>s.hidden)'),'Both dropdowns use the themed control');
    assert(await evaluate('(()=>{const t=document.querySelector("#calendar-scope-trigger"),c=t.querySelector("svg"),b=t.getBoundingClientRect(),x=c.getBoundingClientRect();return b.right-x.right>=15&&b.right-x.right<=18&&t.getAttribute("role")==="combobox"&&document.getElementById(t.getAttribute("aria-labelledby")).textContent==="Tampilkan task dari"})()'),'Chevron is inset and control retains its label');
    await pointerClick('#calendar-scope-trigger');await pause(55);
    assert(await evaluate('(()=>{const p=document.querySelector("#calendar-scope-options");return p.matches(":popover-open")&&Number(getComputedStyle(p).opacity)>0&&Number(getComputedStyle(p).opacity)<1&&document.activeElement.id==="calendar-scope-trigger"})()'),'Themed option list appears smoothly without stealing focus');
    await pause(170);
    assert(await evaluate('(()=>{const p=document.querySelector("#calendar-scope-options"),t=document.querySelector("#calendar-scope-trigger"),o=p.querySelector("[aria-selected=true]");return getComputedStyle(p).backgroundColor==="rgb(255, 253, 245)"&&getComputedStyle(o).backgroundColor==="rgb(60, 84, 70)"&&Math.abs(p.getBoundingClientRect().width-t.getBoundingClientRect().width)<1&&p.scrollWidth===p.clientWidth})()'),'Options use paper and forest colors and align with the field');
    let dropdownShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'dropdown-calendar-light.png'),Buffer.from(dropdownShot.data,'base64'));
    await pointerClick('#calendar-scope-option-1');await pause(300);
    assert(await evaluate('document.querySelector("#calendar-scope").value==="all"&&document.querySelector("#calendar-scope-trigger .dropdown-value").textContent==="Semua grup"&&document.querySelectorAll("#calendar-tasks .calendar-task").length===2'),'Pointer selection updates calendar scope');
    await key('ArrowDown','ArrowDown',40);await key('Home','Home',36);await key('Escape','Escape',27);await pause(170);
    assert(await evaluate('document.querySelector("#calendar-dialog").open&&document.querySelector("#calendar-scope").value==="all"&&document.querySelector("#calendar-scope-options").hidden'),'Escape cancels a preview without closing the calendar');
    await key('ArrowDown','ArrowDown',40);await key('Home','Home',36);await key('Enter','Enter',13);await pause(300);
    assert(await evaluate('document.querySelector("#calendar-scope").value==="current"&&document.querySelectorAll("#calendar-tasks .calendar-task").length===1'),'Keyboard selection updates the calendar');
    await key('s','KeyS',83);assert(await evaluate('document.querySelector("#calendar-scope-trigger").getAttribute("aria-activedescendant")==="calendar-scope-option-1"'),'Typing finds the matching option');
    await key('Escape','Escape',27);await pause(170);
    await pointerClick('#calendar-scope-trigger');await pause(200);await pointerClick('#calendar-day-title');await pause(170);
    assert(await evaluate('document.querySelector("#calendar-scope-options").hidden&&document.querySelector("#calendar-dialog").open&&document.querySelector("#calendar-scope").value==="current"'),'Outside click dismisses only the dropdown and preserves selection');
    await evaluate('for(let i=0;i<6;i++)document.querySelector("#calendar-scope-trigger").click()');await pause(230);
    assert(await evaluate('document.querySelector("#calendar-scope-options").hidden&&document.querySelector("#calendar-scope-options").getAnimations().length===0'),'Rapid toggles settle without leaving a popup');
    console.log('PASS themed dropdowns, inset chevron, aligned options, pointer/keyboard/typeahead, Escape/outside dismissal, and interruptible motion');
    const originalMonth=await evaluate('document.querySelector("#calendar-month").textContent');
    await click('#next-month');await pause(65);
    assert(await evaluate('(()=>{const e=document.querySelector("#calendar-grid"),x=e.getBoundingClientRect().left-e.parentElement.getBoundingClientRect().left;return x>0&&Number(getComputedStyle(e).opacity)>0&&Number(getComputedStyle(e).opacity)<1})()'),'Next month slides in from the right');
    assert(await evaluate('[...document.querySelectorAll(".motion-snapshot")].every(e=>e.inert&&e.getAttribute("aria-hidden")==="true"&&!e.id&&!e.querySelector("[id], [aria-live]"))'),'Outgoing content is inert and has no duplicate IDs or announcements');
    await click('#previous-month');await pause(65);
    assert(await evaluate('(()=>{const e=document.querySelector("#calendar-grid");return e.getBoundingClientRect().left<e.parentElement.getBoundingClientRect().left})()'),'Previous month slides in from the left');
    await evaluate('for(let i=0;i<4;i++)document.querySelector("#next-month").click();for(let i=0;i<4;i++)document.querySelector("#previous-month").click()');await pause(320);
    assert.equal(await evaluate('document.querySelector("#calendar-month").textContent'),originalMonth);
    assert.equal(await evaluate('document.querySelectorAll("#calendar-grid .calendar-cell").length'),42);
    assert.equal(await evaluate('document.querySelectorAll(".motion-snapshot").length'),0);
    const dayHeight=()=>evaluate('document.querySelector("#calendar-day-view").offsetHeight');
    const oldDayHeight=await dayHeight();
    await evaluate('window.chosenDay=[...document.querySelectorAll("#calendar-grid .calendar-cell")].find(e=>!e.classList.contains("outside")&&!e.classList.contains("selected"));chosenDay.click()');await pause(65);
    assert(await evaluate('chosenDay.isConnected&&document.activeElement===chosenDay&&chosenDay.getAttribute("aria-pressed")==="true"'),'Day selection retains the focused button');
    assert(await evaluate('document.querySelector("#calendar-day-view").getAnimations().some(a=>a.playState==="running")'),'Day details animate');
    const middleDayHeight=await dayHeight();await pause(260);const newDayHeight=await dayHeight();
    assert(middleDayHeight<oldDayHeight&&middleDayHeight>newDayHeight,'Day details shrink smoothly when the selected day has fewer tasks');
    await evaluate('const cells=[...document.querySelectorAll("#calendar-grid .calendar-cell")].filter(e=>!e.classList.contains("outside"));for(let i=0;i<8;i++)cells[i].click();document.querySelector("#calendar-today").click()');await pause(320);
    assert.equal(await evaluate('document.querySelectorAll("#calendar-tasks .calendar-task").length'),1);
    assert.equal(await evaluate('document.querySelectorAll(".motion-snapshot").length'),0);
    assert(await evaluate('document.querySelector("#calendar-day-view").style.overflow===""&&document.querySelector("#calendar-day-view").getAnimations().length===0'));
    assert(await evaluate('(()=>{const e=document.querySelector("#calendar-dialog");return e.scrollWidth===e.clientWidth})()'),'Calendar motion does not create horizontal scrolling');
    console.log('PASS menu entry/exit, add-panel and calendar entry, directional months, smooth day sizing, focus, and rapid navigation cleanup');
    await evaluate('document.querySelector("#calendar-scope").value="all";document.querySelector("#calendar-scope").dispatchEvent(new Event("change"))');
    assert.equal(await evaluate('document.querySelectorAll("#calendar-tasks .calendar-task").length'),2);
    await click('.calendar-task');await warm();assert.equal((await stored()).activeGroupId,groupA);assert(!(await evaluate('document.querySelector("#calendar-dialog").open')));
    assert.equal(await evaluate('document.querySelector(".paper:not([hidden])").querySelector(".task-checkbox").checked'),true);
    console.log('PASS group selection, sidebar tracking, calendar current/all groups, calendar task navigation');
    await click('#toggle-create');await click('#open-assets');await click('.asset-choice');await warm();assert.equal((await stored()).assets.length,1);
    await drag('.board-asset',30,20);const assetSaved=(await stored()).assets[0];await send('Page.reload');await waitFor('document.querySelector(".board-asset")');await warm();assert.equal((await stored()).assets[0].x,assetSaved.x);
    await click('.asset-remove');assert.equal((await stored()).assets.length,0);
    await click('.paper:not([hidden]) .paper-options');await pause(300);
    assert(await evaluate('document.querySelector("#card-group-input-trigger .dropdown-value").textContent==="Grup saya"'),'Dynamic group dropdown initially reflects the card group');
    await pointerClick('#card-group-input-trigger');await pause(200);
    assert(await evaluate('(()=>{const p=document.querySelector("#card-group-input-options"),b=p.getBoundingClientRect();return p.matches(":popover-open")&&p.children.length===2&&b.bottom<=innerHeight&&document.elementFromPoint(b.left+15,b.bottom-15).closest(".dropdown-options")===p})()'),'Group list is usable above dialog overflow');
    dropdownShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'dropdown-card-groups.png'),Buffer.from(dropdownShot.data,'base64'));
    await pointerClick('#card-group-input-option-1');await evaluate('document.querySelector("#card-title-input").value="Renamed paper";document.querySelector("#card-settings-form").requestSubmit()');await warm();
    assert.equal((await stored()).activeGroupId,groupB);assert((await stored()).cards.some(c=>c.title==='Renamed paper'&&c.groupId===groupB));
    console.log('PASS asset catalog, asset drag/persistence/removal, card rename/move to group');
    await click('#theme-toggle');await pause(400);assert(await evaluate('document.body.classList.contains("dark")'));assert(await evaluate('getComputedStyle(document.querySelector(".paper:not([hidden])")).backgroundColor==="rgb(255, 253, 245)"'));assert(await evaluate('getComputedStyle(document.querySelector(".paper:not([hidden]) .task-input")).color==="rgb(0, 0, 0)"'));
    await click('#open-calendar');await pause(300);await pointerClick('#calendar-scope-trigger');await pause(220);
    assert(await evaluate('getComputedStyle(document.querySelector("#calendar-scope-options")).backgroundColor==="rgb(48, 43, 37)"&&getComputedStyle(document.querySelector("#calendar-scope-trigger")).color==="rgb(255, 253, 245)"'),'Dropdowns match the dark board controls');
    dropdownShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'dropdown-calendar-dark.png'),Buffer.from(dropdownShot.data,'base64'));await click('#calendar-dialog .dialog-close');await pause(150);
    assert(await evaluate('document.querySelector("#calendar-scope-options").hidden'),'Closing a dialog cleans up its dropdown');
    await click('#reset-view');await warm();let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-dark.png'),Buffer.from(shot.data,'base64'));
    await click('#theme-toggle');await warm();shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-light.png'),Buffer.from(shot.data,'base64'));
    await click('#open-calendar');await warm();shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-calendar.png'),Buffer.from(shot.data,'base64'));await click('#calendar-dialog .dialog-close');
    await send('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await warm();
    assert(await evaluate('document.documentElement.scrollWidth===innerWidth'));
    assert(await evaluate('(()=>{const p=document.querySelector(".paper:not([hidden])").getBoundingClientRect();return p.left>=0&&p.right<=innerWidth&&p.top>=72&&p.bottom<=innerHeight})()'));
    const tap=async selector=>{const p=await point(selector);await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
    const mobileFixedPaper=await paperBounds();assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert'),'Mobile board starts in focus mode after resize');
    await tap('#focus-mode');await pause(300);
    assert(await evaluate('!document.querySelector("#sidebar").inert&&!document.querySelector("#workspace-toolbar").inert'),'The remaining button opens both mobile panels');
    assert.deepEqual(await paperBounds(),mobileFixedPaper,'Mobile panels overlay the fixed board');
    panelShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-mobile-panels.png'),Buffer.from(panelShot.data,'base64'));
    await tap('#rename-group');await pause(300);assert(await evaluate('document.querySelector("#name-dialog").open'),'Mobile toolbar stays clickable while the sidebar is open');await key('Escape','Escape',27);await pause(180);
    assert(await evaluate('!document.querySelector("#sidebar").inert&&!document.querySelector("#workspace-toolbar").inert'),'Dialog Escape preserves the open panels');
    await evaluate('document.querySelector("#theme-toggle").focus()');await key('Tab','Tab',9);assert.equal(await evaluate('document.activeElement.id'),'focus-mode','Focus button participates in the mobile panel keyboard loop');
    await key('Tab','Tab',9);assert(await evaluate('document.activeElement.classList.contains("group-button")'));
    await key('Escape','Escape',27);await pause(300);assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert&&document.activeElement.id==="focus-mode"'));
    await tap('#focus-mode');await pause(300);await send('Page.reload');await waitFor('window.boardWorkspace&&document.querySelector(".paper")');await warm();
    assert(await evaluate('!document.querySelector("#sidebar").inert&&!document.querySelector("#workspace-toolbar").inert'),'Refresh restores both opened mobile panels');
    await tap('#focus-mode');await pause(300);assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#workspace-toolbar").inert'),'Mobile focus mode remains reachable when the drawer is open');
    panelShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'panels-focus-mobile.png'),Buffer.from(panelShot.data,'base64'));
    await tap('#focus-mode');await pause(300);assert(await evaluate('!document.querySelector("#sidebar").inert&&!document.querySelector("#workspace-toolbar").inert'));
    await key('Tab','Tab',9);assert(await evaluate('document.activeElement.classList.contains("group-button")'),'Keyboard enters the mobile drawer from the focus button');
    await click('#sidebar-backdrop');await pause(300);
    assert.deepEqual(await paperBounds(),mobileFixedPaper,'Mobile focus mode and refresh retain paper coordinates');
    console.log('PASS mobile focus-only touch controls, drawer keyboard loop, saved visibility and access to both panels');
    await openPanels();await pause(300);const mobilePaperLink=await point(workLink);
    await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...mobilePaperLink,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(70);
    assert(await evaluate('document.querySelector("#sidebar").inert&&document.querySelector("#board-world").getAnimations().some(a=>a.playState==="running")'),'Touch navigation closes the drawer and moves the board smoothly');
    await pause(400);assert.equal(await evaluate('document.activeElement.closest(".paper").dataset.cardId'),workCard.id);
    assert(await evaluate('(()=>{const p=document.activeElement.closest(".paper").getBoundingClientRect();return p.left>=0&&p.right<=innerWidth&&p.top>=72&&p.bottom<=innerHeight})()'),'Mobile navigation lands with the whole paper visible');
    await openPanels();await click(firstLink);await pause(470);
    await click('#reset-view');await warm();const touchPoint=await point('.paper:not([hidden]) .paper-drag-handle');const touchBefore=(await stored()).cards.find(c=>c.groupId===groupB);
    await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...touchPoint,id:1}]});await pause(200);
    await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchPoint.x+20,y:touchPoint.y+25,id:1}]});await pause(100);await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(250);
    const touchAfter=(await stored()).cards.find(c=>c.id===touchBefore.id);assert(touchAfter.x>touchBefore.x);assert(!await evaluate('document.body.classList.contains("is-paper-dragging")'));
    await click('#reset-view');await warm();shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-mobile.png'),Buffer.from(shot.data,'base64'));
    await click('#open-calendar');await pause(70);
    assert(await evaluate('document.querySelector("#calendar-dialog").getAnimations().some(a=>a.playState==="running")'),'Mobile calendar enters smoothly');
    await pause(250);await click('#next-month');await pause(65);
    assert(await evaluate('document.querySelector("#calendar-grid").getAnimations().some(a=>a.playState==="running")'),'Month motion works on mobile');
    await evaluate('[...document.querySelectorAll("#calendar-grid .calendar-cell")].find(e=>!e.classList.contains("outside")&&!e.classList.contains("selected")).click()');await pause(65);
    assert(await evaluate('document.querySelector("#calendar-day-view").getAnimations().some(a=>a.playState==="running")'),'Day motion works on mobile');
    assert(await evaluate('(()=>{const e=document.querySelector("#calendar-dialog");return e.scrollWidth===e.clientWidth})()'),'Mobile motion creates no horizontal scrolling');
    await pause(300);assert.equal(await evaluate('document.querySelectorAll(".motion-snapshot").length'),0);
    await click('#calendar-dialog .dialog-close');
    await click('#open-calendar');await pause(300);const mobileScope=await point('#calendar-scope-trigger');
    await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...mobileScope,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(220);
    assert(await evaluate('(()=>{const p=document.querySelector("#calendar-scope-options"),b=p.getBoundingClientRect();return p.matches(":popover-open")&&b.left>=0&&b.right<=innerWidth&&b.bottom<=innerHeight})()'),'Mobile option list fits the screen');
    dropdownShot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'dropdown-calendar-mobile.png'),Buffer.from(dropdownShot.data,'base64'));
    const mobileOption=await point('#calendar-scope-option-1');await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...mobileOption,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(300);
    assert(await evaluate('document.querySelector("#calendar-scope").value==="all"'),'Touch selects the themed option');await click('#calendar-dialog .dialog-close');
    await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Page.reload');await waitFor('document.querySelector(".paper")');await pause(200);
    assert(await evaluate('!document.querySelector(".paper:not([hidden])").classList.contains("is-entering")'));
    await openPanels();assert(await evaluate('!document.querySelector("#workspace-toolbar").inert&&document.querySelector("#workspace-toolbar").getAnimations().length===0&&document.querySelector("#sidebar").getAnimations().length===0'),'Reduced motion removes panel sliding');
    await click(secondLink);
    assert(await evaluate('!document.querySelector(".group-transition")&&document.querySelector("#board-world").getAnimations().length===0&&document.querySelector("#card-layer").getAnimations().length===0'),'Reduced motion skips sidebar movement and group fades');
    await openPanels();await click(workLink);
    assert.equal((await stored()).activeGroupId,groupB);
    await click('#toggle-create');assert(await evaluate('!document.querySelector("#create-menu").hidden&&document.querySelector("#create-menu").getAnimations().length===0'));
    await click('#create-card');assert(await evaluate('document.querySelector("#name-dialog").open&&document.querySelector("#name-dialog").getAnimations().length===0&&document.querySelector("#create-menu").hidden'));
    await click('#name-dialog .dialog-close');await click('#open-calendar');await click('#next-month');
    await click('#calendar-scope-trigger');assert(await evaluate('document.querySelector("#calendar-scope-options").getAnimations().length===0'),'Reduced motion disables dropdown animation');await key('Escape','Escape',27);
    await evaluate('[...document.querySelectorAll("#calendar-grid .calendar-cell")].find(e=>!e.classList.contains("outside")&&!e.classList.contains("selected")).click()');
    assert(await evaluate('document.querySelectorAll(".motion-snapshot").length===0&&document.querySelector("#calendar-grid").getAnimations().length===0&&document.querySelector("#calendar-day-view").getAnimations().length===0&&document.querySelector("#calendar-dialog").getAnimations().length===0'),'Reduced motion removes popup, month, and day animations');
    await click('#calendar-dialog .dialog-close');
    console.log('PASS light paper in dark board, mobile layout, sidebar, touch drag, reduced motion');
    await waitFor('navigator.serviceWorker.controller!==null');await send('Network.enable');
    const installability=await send('Page.getInstallabilityErrors');assert.deepEqual(installability.installabilityErrors,[]);
    const manifest=await (await fetch(url.replace('index.html','manifest.webmanifest'))).json();assert.equal(manifest.icons.length,3);
    assert(await evaluate('caches.keys().then(names=>names.find(name=>name.startsWith("my-todo-board-shell-"))).then(name=>caches.open(name)).then(c=>c.keys()).then(keys=>keys.length>=20)'));
    const offlineBefore=await stored();await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});
    await send('Page.reload');await waitFor('document.querySelectorAll(".paper").length===3');await warm();
    assert.equal((await stored()).cards.length,offlineBefore.cards.length);assert.equal(await evaluate('document.querySelector("#connection-status").textContent'),'Offline');
    assert.equal(await evaluate('document.querySelectorAll(".dropdown-trigger").length'),2,'Themed dropdowns load offline');
    assert(await evaluate('typeof window.boardPanels.dismissSidebar==="function"&&getComputedStyle(document.querySelector("#focus-mode")).position==="fixed"&&!document.querySelector(".panel-tab, .board-hint")'),'Focus-only panel control loads offline');
    await add('.paper:not([hidden])','Offline task');assert((await stored()).cards.some(c=>c.tasks.some(t=>t.text==='Offline task')));
    await send('Page.reload');await waitFor('document.querySelectorAll(".paper").length===3');await warm();assert((await stored()).cards.some(c=>c.tasks.some(t=>t.text==='Offline task')));
    await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
    console.log('PASS valid installability, bundled icon manifest, service-worker cache, offline reload/edit/persistence');
    await send('Emulation.setEmulatedMedia',{features:[]});
    await send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});
    await send('Emulation.setTouchEmulationEnabled',{enabled:false});
    await click('[data-link-id="'+workCard.id+'"]');await warm();
    const height=()=>evaluate('document.querySelector('+JSON.stringify(workSelector+' .task-list')+').getBoundingClientRect().height/window.boardWorkspace.zoom');
    const beforeHeight=await height();
    await evaluate('(()=>{const p=document.querySelector('+JSON.stringify(workSelector)+');p.querySelector(".task-input").value="Animated addition";p.querySelector(".task-form").requestSubmit()})()');
    await pause(90);const middleHeight=await height();await pause(400);const afterHeight=await height();
    assert(middleHeight>beforeHeight&&middleHeight<afterHeight,'Short lists grow smoothly');
    await evaluate('document.querySelectorAll('+JSON.stringify(workSelector+' .task-checkbox')+').forEach(c=>{if(!c.checked)c.click()})');await pause(400);
    assert.equal(await evaluate('document.querySelector('+JSON.stringify(workSelector+' .counter-number')+').dataset.value'),'0');
    assert.equal(await evaluate('document.querySelectorAll('+JSON.stringify(workSelector+' .counter-digit')+').length'),1);
    await click(workSelector+' .clear-completed');await pause(70);assert(await evaluate('document.querySelectorAll('+JSON.stringify(workSelector+' .removing')+').length===2'));
    await pause(600);assert.equal((await stored()).cards.find(c=>c.id===workCard.id).tasks.length,0);
    for(const text of ['Alpha','Beta','Gamma'])await add(workSelector,text);
    await evaluate('(()=>{const p=document.querySelector('+JSON.stringify(workSelector)+'),l=p.querySelector(".task-list"),a=l.firstElementChild,b=l.lastElementChild,d=new DataTransfer();b.dispatchEvent(new DragEvent("dragstart",{bubbles:true,dataTransfer:d}));l.dispatchEvent(new DragEvent("dragover",{bubbles:true,cancelable:true,dataTransfer:d,clientY:a.getBoundingClientRect().top+1}));l.dispatchEvent(new DragEvent("drop",{bubbles:true,cancelable:true,dataTransfer:d}));b.dispatchEvent(new DragEvent("dragend",{bubbles:true,dataTransfer:d}));})()');
    assert.deepEqual((await stored()).cards.find(c=>c.id===workCard.id).tasks.map(t=>t.text),['Gamma','Alpha','Beta']);
    const keyboardBefore=(await stored()).cards.find(c=>c.id===workCard.id);
    await evaluate('document.querySelector('+JSON.stringify(workSelector+' .paper-drag-handle')+').focus()');
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',modifiers:8});
    await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',modifiers:8});await pause(200);
    assert.equal((await stored()).cards.find(c=>c.id===workCard.id).x,keyboardBefore.x+40);
    const escapeBefore=(await stored()).cards.find(c=>c.id===workCard.id);const grip=await point(workSelector+' .paper-drag-handle');
    await mouse('mousePressed',grip);await mouse('mouseMoved',{x:grip.x+50,y:grip.y+30});
    await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});
    await mouse('mouseReleased',{x:grip.x+50,y:grip.y+30});await pause(250);
    assert.equal((await stored()).cards.find(c=>c.id===workCard.id).x,escapeBefore.x);
    await evaluate('window.installCalls=0;const e=new Event("beforeinstallprompt",{cancelable:true});e.prompt=async()=>{window.installCalls++};e.userChoice=Promise.resolve({outcome:"accepted"});window.dispatchEvent(e)');
    await click('#install-button');assert.equal(await evaluate('window.installCalls'),1);
    await evaluate('window.dispatchEvent(new Event("appinstalled"))');assert(await evaluate('document.querySelector("#install-button").disabled'));
    // Long task text must wrap within its own row in the capped scroll viewport.
    await add(workSelector,'longword'.repeat(65));await warm();
    assert(await evaluate('(()=>{const l=document.querySelector('+JSON.stringify(workSelector+' .task-list')+');return l.scrollWidth<=l.clientWidth+1&&l.scrollHeight>l.clientHeight})()'));
    await click(workSelector+' .paper-options');await click('#delete-card');assert.equal((await stored()).cards.length,3);
    await click('#delete-card');assert.equal((await stored()).cards.length,2);
    console.log('PASS short-card resizing, rapid counters, bulk deletion, reorder, keyboard/Escape drag, install event flow, long text, card deletion');
    await click('#add-group');assert(await evaluate('document.querySelector("#delete-group").hidden'),'Group creation does not offer deletion');await submitName('Temporary group');
    const disposableId=(await stored()).activeGroupId;
    await click('#empty-create');assert(await evaluate('document.querySelector("#delete-group").hidden'),'Card creation does not offer group deletion');await submitName('Disposable paper');
    const disposableCard=(await stored()).cards.find(c=>c.groupId===disposableId);
    await add('.paper[data-card-id="'+disposableCard.id+'"]','Disposable deadline',due);
    await click('#toggle-create');await click('#open-assets');await click('.asset-choice');await warm();
    await click('#rename-group');await submitName('Delete "this" <group>');
    assert(await evaluate('!document.querySelector("#group-list .group-delete")&&!document.querySelector(".current-group small")'),'Sidebar delete icons and the PAPAN label are removed');
    await click('#rename-group');await pause(300);
    const deleteSelector='#delete-group';
    assert(await evaluate('!document.querySelector("#delete-group").hidden&&document.querySelector("#name-dialog-title").textContent==="Ubah nama grup"'),'Group deletion is offered inside the edit dialog');
    await evaluate('document.querySelector("#name-input").value="Unsaved group title"');
    shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-edit-group.png'),Buffer.from(shot.data,'base64'));
    const beforeGroupDelete=await stored();
    const deletePoint=await point(deleteSelector);await mouse('mousePressed',deletePoint);await mouse('mouseReleased',deletePoint);await pause(70);
    assert(await evaluate('document.querySelector("#delete-group-dialog").open&&document.activeElement.textContent==="Batal"'),'Deleting a group opens a confirmation with Cancel focused');
    assert(await evaluate('document.querySelector("#delete-group-message").textContent.includes("1 kertas, 1 task, dan 1 aset")&&!document.querySelector("#delete-group-message").querySelector("group")'),'Confirmation includes escaped group name and accurate content counts');
    assert.equal((await stored()).activeGroupId,disposableId,'Opening the confirmation keeps the group selected');
    await click('#delete-group-dialog .secondary-button');assert.deepEqual(await stored(),beforeGroupDelete,'Cancel leaves all data unchanged');
    assert(await evaluate('document.querySelector("#name-dialog").open&&document.querySelector("#name-input").value==="Unsaved group title"&&document.activeElement===document.querySelector("#delete-group")'),'Cancel returns to the edit dialog without losing unsaved text');
    await click(deleteSelector);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await pause(150);
    assert(await evaluate('!document.querySelector("#delete-group-dialog").open&&document.querySelector("#name-dialog").open'),'Escape cancels deletion and returns to the editor');assert.deepEqual(await stored(),beforeGroupDelete);
    await click(deleteSelector);await click('#confirm-delete-group');await pause(450);
    const afterGroupDelete=await stored();
    assert.equal(afterGroupDelete.activeGroupId,groupB);
    assert.deepEqual(afterGroupDelete.groups,beforeGroupDelete.groups.filter(g=>g.id!==disposableId),'Remaining group cameras and names are preserved');
    assert.deepEqual(afterGroupDelete.cards,beforeGroupDelete.cards.filter(c=>c.groupId!==disposableId),'Only the deleted group cards/tasks are removed');
    assert.deepEqual(afterGroupDelete.assets,beforeGroupDelete.assets.filter(a=>a.groupId!==disposableId));
    assert(await evaluate('!document.querySelector('+JSON.stringify('.paper[data-card-id="'+disposableCard.id+'"]')+')&&!document.querySelector('+JSON.stringify('.group-section[data-group-id="'+disposableId+'"]')+')&&!document.querySelector(".board-asset")'),'Deleted cards, assets, and sidebar row are unmounted');
    assert(await evaluate('!document.querySelector("#name-dialog").open&&!document.querySelector("#delete-group-dialog").open'),'Confirmed deletion closes both dialogs');
    assert(await evaluate('document.activeElement===document.querySelector("#board-viewport")'),'Deletion restores focus to the board');
    await click('#open-calendar');await evaluate('document.querySelector("#calendar-scope").value="all";document.querySelector("#calendar-scope").dispatchEvent(new Event("change"))');await pause(300);
    const remainingDeadlines=afterGroupDelete.cards.reduce((count,c)=>count+c.tasks.filter(t=>t.dueDate===due).length,0);
    assert.equal(await evaluate('document.querySelectorAll("#calendar-tasks .calendar-task").length'),remainingDeadlines,'Calendar no longer includes deleted group deadlines');
    await click('#calendar-dialog .dialog-close');
    await send('Page.reload');await waitFor('window.boardWorkspace&&document.querySelectorAll(".paper").length===2');await warm();
    assert.deepEqual((await stored()).cards,afterGroupDelete.cards,'Group deletion persists through reload');
    // Delete the active group on mobile, then the final group. Old migration data must stay gone.
    await send('Emulation.setDeviceMetricsOverride',{width:375,height:812,deviceScaleFactor:1,mobile:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await warm();
    const mobileGroup=(await stored()).activeGroupId;
    await click('#rename-group');await pause(300);
    const mobileDelete=await point('#delete-group');
    await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...mobileDelete,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(300);
    assert(await evaluate('document.querySelector("#delete-group-dialog").open&&document.querySelector("#delete-group-last-note").hidden'),'Mobile edit action opens the same confirmation');
    await click('#confirm-delete-group');await pause(350);
    const survivingGroup=await stored();assert.equal(survivingGroup.groups.length,1);assert.notEqual(survivingGroup.activeGroupId,mobileGroup);
    assert(!survivingGroup.cards.some(c=>c.groupId===mobileGroup));assert(await evaluate('document.querySelector("#sidebar").inert&&document.activeElement===document.querySelector("#board-viewport")'));
    await click('#rename-group');await click('#delete-group');assert(await evaluate('!document.querySelector("#delete-group-last-note").hidden'));
    await click('#confirm-delete-group');await pause(350);
    const emptyReplacement=await stored();assert.equal(emptyReplacement.groups.length,1);assert.equal(emptyReplacement.cards.length,0);assert.equal(emptyReplacement.assets.length,0);assert.notEqual(emptyReplacement.activeGroupId,survivingGroup.activeGroupId);
    await send('Page.reload');await waitFor('window.boardWorkspace&&!document.querySelector("#empty-board").hidden');await warm();
    assert.equal((await stored()).cards.length,0,'Reloading after the final group is deleted does not resurrect legacy tasks');
    await openPanels();await pause(300);
    assert(await evaluate('(()=>{const e=document.querySelector("#group-list");return e.scrollWidth===e.clientWidth&&!e.querySelector(".group-delete")&&document.documentElement.scrollWidth===innerWidth})()'),'Mobile sidebar fits without horizontal scrolling or delete icons');
    await click('#sidebar-backdrop');
    await click('#rename-group');await pause(300);
    assert(await evaluate('(()=>{const d=document.querySelector("#name-dialog"),b=document.querySelector("#delete-group").getBoundingClientRect();return d.scrollWidth===d.clientWidth&&b.width>=44&&b.height>=44})()'),'Edit dialog delete action fits the mobile dialog');
    shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(artifactDir,'workspace-edit-group-mobile.png'),Buffer.from(shot.data,'base64'));await click('#name-dialog .secondary-button');
    console.log('PASS deletion through group edit, hidden actions during creation, removed PAPAN/sidebar icons, preserved editor text on Cancel/Escape, cleanup, calendar/persistence, mobile touch, and last group deletion');
    assert.deepEqual(errors,[],'No browser runtime exceptions');
    console.log('ALL WORKSPACE INTEGRATION CHECKS PASSED');
    await send('Browser.close');
  } finally { if(socket) socket.close();child.kill();server.close();console.log('Screenshots: '+artifactDir); }
})().catch(error=>{console.error(error);process.exitCode=1;});
